version: 2
updates:
  # Configuration for npm
  - package-ecosystem: 'npm'
    directory: .
    schedule:
      # Check the npm registry for updates every Sunday at 4am UTC
      interval: 'weekly'
      day: 'sunday'
      time: '04:00'
    open-pull-requests-limit: 20
    target-branch: 'main'
    labels:
      - 'dependencies'
    ignore:
      # For cypress, ignore all updates. Do manually instead.
      - dependency-name: 'cypress'
